import streamlit as st
import json

from logic import check_order_status, process_return_info, check_stock

# Page Configuration
st.set_page_config(page_title="Northstar Support Hub", page_icon="🛍️")

# Header & Branding
st.title("🛍️ Northstar Retail Support")
st.write("Welcome! Select your request below for instant help.")

# Navigation Tabs for Categories
tab1, tab2, tab3 = st.tabs(["📦 Order Status", "🔄 Returns & Refunds", "🏷️ Stock Check"])

# TAB 1: Order Status
with tab1:
    st.subheader("Where is my order?")
    order_id_input = st.text_input("Enter your Order ID ( ORD1001, ORD1002):", key="status_id")
    
    if st.button("Track Order"):
        if order_id_input:
            response = check_order_status(order_id_input)
            st.info(response)
        else:
            st.warning("Please enter a valid Order ID.")

# TAB 2: Returns & Refunds
with tab2:
    st.subheader("Process a Return or View Policy")
    return_id_input = st.text_input(
        "Enter your Order ID for Returns:",
        key="return_id"
    )

    col1, col2 = st.columns(2)

    with col1:
        if st.button("Check Return Eligibility"):
            if return_id_input:
                response = process_return_info(return_id_input)
                st.success(response)

                # Create a downloadable mock return label
                clean_id = return_id_input.strip().upper()

                label_content = f"""
NORTHSTAR RETAIL CO.
RETURN SHIPPING LABEL
--------------------------------

Order ID: {clean_id}

Customer Return
Please attach this label securely
to your return package.

Return Address:
Northstar Retail Co.
Returns Department
Nairobi, Kenya

--------------------------------
Generated by Northstar Support MVP
"""

                st.download_button(
                    label="📥 Download Return Label",
                    data=label_content,
                    file_name=f"return-label-{clean_id}.txt",
                    mime="text/plain"
                )

            else:
                st.warning("Please enter an Order ID.")

    with col2:
        if st.button("View General Return Policy"):
            response = process_return_info("")
            st.write(response)
# TAB 3: Stock Availability
with tab3:
    st.subheader("Check Item Availability")

    # Load products from inventory.json
    try:
        with open("data/inventory.json", "r", encoding="utf-8") as file:
            inventory_data = json.load(file)

        # Get unique product names
        products = sorted(
            set(product["product_name"] for product in inventory_data)
        )

        prod_input = st.selectbox(
            "Select Product:",
            products
        )

        # Find sizes available for the selected product
        selected_product_data = [
            product
            for product in inventory_data
            if product["product_name"] == prod_input
        ]

        available_sizes = [
            product["size"]
            for product in selected_product_data
        ]

        size_input = st.selectbox(
            "Select Size:",
            available_sizes
        )

        if st.button("Check Stock"):
            response = check_stock(prod_input, size_input)
            st.write(response)

    except FileNotFoundError:
        st.error("Inventory database not found. Please check that data/inventory.json exists.")
    except (json.JSONDecodeError, KeyError) as error:
        st.error(f"Could not read inventory data: {error}")
